from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    """Stable machine-readable outcomes used by logs, CLI, and decisions."""

    NON_LIVE_MODE = "NON_LIVE_MODE"
    LIVE_FLAG_DISABLED = "LIVE_FLAG_DISABLED"
    CI_OR_TEST_ENVIRONMENT = "CI_OR_TEST_ENVIRONMENT"
    LOCAL_UNLOCK_MISSING = "LOCAL_UNLOCK_MISSING"
    TELEGRAM_CHALLENGE_MISSING = "TELEGRAM_CHALLENGE_MISSING"
    CURRENT_QUALIFICATION_MISSING = "CURRENT_QUALIFICATION_MISSING"
    ROUTE_NOT_ALLOWLISTED = "ROUTE_NOT_ALLOWLISTED"
    PREFLIGHT_FAILED = "PREFLIGHT_FAILED"
    SERVICE_HEALTHY = "SERVICE_HEALTHY"
    SERVICE_NOT_RUNNING = "SERVICE_NOT_RUNNING"
    SERVICE_HEARTBEAT_STALE = "SERVICE_HEARTBEAT_STALE"
    SERVICE_STATE_MISSING = "SERVICE_STATE_MISSING"
    CAPABILITY_UNKNOWN = "CAPABILITY_UNKNOWN"
    VENUE_QUARANTINED = "VENUE_QUARANTINED"
    INSTRUMENT_NOT_EQUIVALENT = "INSTRUMENT_NOT_EQUIVALENT"
    BOOK_EMPTY = "BOOK_EMPTY"
    BOOK_CROSSED = "BOOK_CROSSED"
    BOOK_STALE = "BOOK_STALE"
    BOOK_UNSYNCHRONISED = "BOOK_UNSYNCHRONISED"
    BOOK_SEQUENCE_GAP = "BOOK_SEQUENCE_GAP"
    BOOK_SEQUENCE_UNKNOWN = "BOOK_SEQUENCE_UNKNOWN"
    CLOCK_SKEW_UNKNOWN = "CLOCK_SKEW_UNKNOWN"
    CLOCK_SKEW_EXCEEDED = "CLOCK_SKEW_EXCEEDED"
    DEPTH_INSUFFICIENT = "DEPTH_INSUFFICIENT"
    CONTRACT_METADATA_UNKNOWN = "CONTRACT_METADATA_UNKNOWN"
    FEE_UNKNOWN = "FEE_UNKNOWN"
    FUNDING_UNKNOWN = "FUNDING_UNKNOWN"
    MARK_INDEX_UNKNOWN = "MARK_INDEX_UNKNOWN"
    QUOTE_READY = "QUOTE_READY"
