from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    """Stable machine-readable outcomes used by logs, CLI, and decisions."""

    NON_LIVE_MODE = "NON_LIVE_MODE"
    LIVE_FLAG_DISABLED = "LIVE_FLAG_DISABLED"
    CI_OR_TEST_ENVIRONMENT = "CI_OR_TEST_ENVIRONMENT"
    LOCAL_UNLOCK_MISSING = "LOCAL_UNLOCK_MISSING"
    TELEGRAM_CHALLENGE_MISSING = "TELEGRAM_CHALLENGE_MISSING"
    CURRENT_QUALIFICATION_MISSING = "CURRENT_QUALIFICATION_MISSING"
    ROUTE_NOT_ALLOWLISTED = "ROUTE_NOT_ALLOWLISTED"
    PREFLIGHT_FAILED = "PREFLIGHT_FAILED"
    SERVICE_HEALTHY = "SERVICE_HEALTHY"
    SERVICE_NOT_RUNNING = "SERVICE_NOT_RUNNING"
    SERVICE_HEARTBEAT_STALE = "SERVICE_HEARTBEAT_STALE"
    SERVICE_STATE_MISSING = "SERVICE_STATE_MISSING"
